# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
# Formatter to run
command = "nixpkgs-fmt"
# Command-line arguments for the command
options = []
# Glob pattern of files to include
includes = [ "*.nix" ]
# Glob patterns of files to exclude
excludes = []

[formatter.python]
# Formatter to run
command = "black"
# Command-line arguments for the command
options = []
# Glob pattern of files to include
includes = [ "*.py" ]
# Glob patterns of files to exclude
excludes = []

[formatter.lua]
# Formatter to run
command = "stylua"
# Command-line arguments for the command
options = ["--indent-type=Spaces"]
# Glob pattern of files to include
includes = [ "*.lua" ]
# Glob patterns of files to exclude
excludes = []
