name: Bisect nixpkgs input

on:
  workflow_dispatch:

jobs:
  bisect-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          - nixosConfigurations.phil.config.system.build.toplevel
          - homeManagerConfigurations.server.activationPackage
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        path: system
    - name: Checkout nixpkgs
      uses: actions/checkout@v2.4.0
      with:
        repository: NixOS/nixpkgs
        fetch-depth: 0
        path: nixpkgs
    - name: Cleanup disk
      uses: curoky/cleanup-disk-action@v2.0
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Bisect nixpkgs flake input
      run: |
        # Assumes that HEAD points to a flake update commit and extract nixpkgs refs
        GOOD_REF=$(git -C system log --format=%B -1 | grep "'nixpkgs'" | sed "s/\* Updated '.*': '.*\([0-9a-f]\{40\}\)' -> '.*[0-9a-f]\{40\}'/\1/")
        BAD_REF=$(git -C system log --format=%B -1 | grep "'nixpkgs'" | sed "s/\* Updated '.*': '.*[0-9a-f]\{40\}' -> '.*\([0-9a-f]\{40\}\)'/\1/")
        git -C nixpkgs bisect start
        git -C nixpkgs bisect good $GOOD_REF
        git -C nixpkgs bisect bad $BAD_REF
        # Automate git bisect with nix build command
        git -C nixpkgs bisect run nix build $GITHUB_WORKSPACE/system#.${{ matrix.configuration }} --override-input nixpkgs $GITHUB_WORKSPACE/nixpkgs

  bisect-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        configuration:
          - darwinConfigurations.randall.config.system.build.toplevel
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        path: system
    - name: Checkout nixpkgs
      uses: actions/checkout@v2.4.0
      with:
        repository: NixOS/nixpkgs
        fetch-depth: 0
        path: nixpkgs
    - name: Cleanup disk
      uses: curoky/cleanup-disk-action@v2.0
    - uses: cachix/install-nix-action@v16
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Bisect nixpkgs flake input
      run: |
        # Assumes that HEAD points to a flake update commit and extract nixpkgs refs
        GOOD_REF=$(git -C system log --format=%B -1 | grep "'nixpkgs'" | sed "s/\* Updated '.*': '.*\([0-9a-f]\{40\}\)' -> '.*[0-9a-f]\{40\}'/\1/")
        BAD_REF=$(git -C system log --format=%B -1 | grep "'nixpkgs'" | sed "s/\* Updated '.*': '.*[0-9a-f]\{40\}' -> '.*\([0-9a-f]\{40\}\)'/\1/")
        git -C nixpkgs bisect start
        git -C nixpkgs bisect good $GOOD_REF
        git -C nixpkgs bisect bad $BAD_REF
        # Automate git bisect with nix build command
        git -C nixpkgs bisect run nix build $GITHUB_WORKSPACE/system#.${{ matrix.configuration }} --override-input nixpkgs $GITHUB_WORKSPACE/nixpkgs
