name: 'system build'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-11.0
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - uses: cachix/install-nix-action@v13
        env:
          NIX_VERSION: nix-2.4pre20210604_8e6ee1b
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/${{ env.NIX_VERSION }}/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: kclejeune
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run Flake Checks
        run: |
          nix flake check -v --show-trace
        timeout-minutes: 120
